AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 1024

Resources:
  DeejaiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: deejai/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Deejai:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /playlist
            Method: get
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub "deej-ai.online"
    Metadata:
      BuildMethod: makefile
            
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DeejaiApi:
    Description: "API Gateway endpoint URL for Prod stage for Deej-A.I. playlist function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/playlist/"
  DeejaiFunction:
    Description: "Deej-A.I. playlist Lambda Function ARN"
    Value: !GetAtt DeejaiFunction.Arn
  DeejaiFunctionIamRole:
    Description: "Implicit IAM Role created for Deej-A.I. playlist function"
    Value: !GetAtt DeejaiFunctionRole.Arn
